# Generated by Django 4.2 on 2025-08-01 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('others', 'Others')], max_length=10)),
                ('booking_created_time', models.DateTimeField(blank=True, null=True)),
                ('booking_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('storage_image_url', models.URLField(blank=True, null=True)),
                ('storage_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('storage_latitude', models.FloatField(default=0.0)),
                ('storage_longitude', models.FloatField(default=0.0)),
                ('storage_booked_location', models.CharField(blank=True, max_length=100, null=True)),
                ('user_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('assigned_saathi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saathi', to=settings.AUTH_USER_MODEL)),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='storage_units.storageunit')),
                ('user_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='storage_bookings.storagebooking')),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_units.storageunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
