# Generated by Django 4.2 on 2025-08-01 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebooking',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='luggage_rakshak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rakshak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='storage_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagebooking',
            name='assigned_saathi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saathi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storagebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('confirmed', 'Confirmed'), ('pickup', 'Pickup'), ('out_for_delivery', 'Out For Delivery'), ('luggage_Stored', 'Luggage Stored'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
