# Generated by Django 4.2 on 2025-08-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_bookings', '0002_storagebooking_amount_storagebooking_luggage_rakshak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebooking',
            name='delivered_to_rakshak_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='luggage_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='pickup_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='return_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='return_estimated_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='return_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='return_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='return_preferred_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
