# Generated by Django 4.2 on 2025-08-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_bookings', '0003_storagebooking_delivered_to_rakshak_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('confirmed', 'Confirmed'), ('pickup', 'Pickup'), ('out_for_delivery', 'Out For Delivery'), ('luggage_Stored', 'Luggage Stored'), ('luggage_reached', 'Luggage Reached'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
