# Generated by Django 4.2 on 2025-09-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saathi', '0003_alter_saathi_aadhaar_card_upload_link_and_more'),
        ('storage_bookings', '0004_alter_storagebooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebooking',
            name='assigned_saathi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saathi', to='saathi.saathi'),
        ),
    ]
