# Generated by Django 4.2 on 2025-10-12 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage_units', '0003_addon_storageunitaddon_and_more'),
        ('storage_bookings', '0005_alter_storagebooking_assigned_saathi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_addons', to='storage_units.addon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_addons_id', to='storage_bookings.storagebooking')),
            ],
        ),
    ]
