# Generated by Django 4.2 on 2025-11-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_bookings', '0006_counter_bookingaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebooking',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
