# Generated by Django 4.2 on 2025-11-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_bookings', '0008_storagebooking_amount_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('confirmed', 'Confirmed'), ('pickup', 'Pickup'), ('out_for_delivery', 'Out For Delivery'), ('luggage_Stored', 'Luggage Stored'), ('luggage_reached', 'Luggage Reached'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('payment_complete', 'Payment Complete')], default='pending', max_length=20),
        ),
    ]
