# Generated by Django 4.2 on 2025-11-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_bookings', '0009_alter_storagebooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_confirmed', models.BooleanField(default=False)),
                ('booking_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('luggage_stored', models.BooleanField(default=False)),
                ('luggage_stored_at', models.DateTimeField(blank=True, null=True)),
                ('payment_initiated', models.BooleanField(default=False)),
                ('payment_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('booking_completed', models.BooleanField(default=False)),
                ('booking_completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking_cancelled', models.BooleanField(default=False)),
                ('booking_cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='storage_bookings.storagebooking')),
            ],
        ),
    ]
