# Generated by Django 4.2 on 2025-11-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_bookings', '0010_bookingstatushistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingstatushistory',
            old_name='payment_initiated',
            new_name='payment_completed',
        ),
        migrations.RenameField(
            model_name='bookingstatushistory',
            old_name='payment_initiated_at',
            new_name='payment_completed_at',
        ),
    ]
