# Generated by Django 4.2 on 2025-11-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_units', '0004_stoargenearbyplace'),
        ('storage_bookings', '0011_rename_payment_initiated_bookingstatushistory_payment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingaddon',
            name='addon_str_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingaddon',
            name='booking_str_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingaddon',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_addons', to='storage_units.addon'),
        ),
        migrations.AlterField(
            model_name='bookingaddon',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_addons_id', to='storage_bookings.storagebooking'),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='storage_bookings.storagebooking'),
        ),
    ]
