# Generated by Django 4.2 on 2025-11-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_bookings', '0012_bookingaddon_addon_str_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebooking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
