# Generated by Django 4.2 on 2025-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_bookings', '0013_storagebooking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebooking',
            name='ending_soon_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagebooking',
            name='late_pickup_notified',
            field=models.BooleanField(default=False),
        ),
    ]
