# Generated by Django 4.2 on 2025-11-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_bookings', '0014_storagebooking_ending_soon_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebooking',
            name='booked_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
