# Generated by Django 4.2 on 2025-08-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageunit',
            old_name='price_per_day',
            new_name='price_per_km',
        ),
    ]
