# Generated by Django 4.2 on 2025-10-12 08:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage_units', '0002_rename_price_per_day_storageunit_price_per_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnitAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_unit_addons', to='storage_units.addon')),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_unit_addons', to='storage_units.storageunit')),
            ],
        ),
        migrations.AddIndex(
            model_name='storageunitaddon',
            index=models.Index(fields=['storage_unit'], name='storage_uni_storage_01ff77_idx'),
        ),
        migrations.AddIndex(
            model_name='storageunitaddon',
            index=models.Index(fields=['addon'], name='storage_uni_addon_i_67b15f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storageunitaddon',
            unique_together={('storage_unit', 'addon')},
        ),
    ]
