# Generated by Django 4.2 on 2025-10-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_units', '0003_addon_storageunitaddon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoargeNearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('place_name', models.CharField(blank=True, max_length=200, null=True)),
                ('place_description', models.TextField(blank=True, null=True)),
                ('distance_km', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
