# Generated by Django 4.2 on 2025-08-09 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saathi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pan_card_number', models.CharField(max_length=10, unique=True)),
                ('aadhaar_card_number', models.CharField(max_length=12, unique=True)),
                ('pan_card_upload_link', models.CharField(max_length=200, unique=True)),
                ('aadhaar_card_upload_link', models.CharField(max_length=200, unique=True)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saathi_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saathi',
                'verbose_name_plural': 'Saathis',
            },
        ),
    ]
