# Generated by Django 4.2 on 2025-08-12 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saathi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saathi',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='saathi',
            name='user',
        ),
        migrations.AddField(
            model_name='saathi',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saathi',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saathi',
            name='document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saathi',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saathi',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saathi',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saathi',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saathi',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='saathi',
            name='otp_generated_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saathi',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='saathi',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='saathi',
            name='profile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saathi',
            name='role',
            field=models.CharField(default='saathi', max_length=20),
        ),
        migrations.AddField(
            model_name='saathi',
            name='terms_and_condition_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='saathi',
            name='aadhaar_card_upload_link',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='saathi',
            name='pan_card_upload_link',
            field=models.TextField(unique=True),
        ),
    ]
