# Generated by Django 4.2 on 2025-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saathi', '0002_remove_saathi_gender_remove_saathi_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saathi',
            name='aadhaar_card_upload_link',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='saathi',
            name='pan_card_upload_link',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
