# Generated by Django 4.2 on 2025-08-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
