# Generated by Django 4.2 on 2025-09-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdevicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='actionRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
