# Generated by Django 4.2 on 2025-11-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
