# Generated by Django 4.2 on 2025-12-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_partnerunitmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('shathi', 'Shathi'), ('locker_owner', 'Locker Owner'), ('admin', 'Admin'), ('partner', 'Partner')], default='user', max_length=20),
        ),
    ]
