# Generated by Django 4.2 on 2025-12-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_units', '0004_stoargenearbyplace'),
        ('users', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerunitmapping',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_mappings', to='storage_units.storageunit'),
        ),
    ]
