# Generated by Django 4.2 on 2025-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('booking', 'Booking Payment'), ('refund', 'Refund'), ('referral_reward', 'Referral Reward'), ('cashback', 'Cashback'), ('adjustment', 'Manual Adjustment'), ('return_payment', 'Return Payment'), ('signup_bonus', 'Signup Bonus')], max_length=20),
        ),
    ]
