# Generated by Django 4.2 on 2025-08-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='raw_response_from_razorpay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
